name: Validate infrastructure

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  opentofu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: opentofu/setup-opentofu@9d84900f3238fab8cd84ce47d658d25dd008be2f
        with:
          tofu_version: 1.13.1
          tofu_wrapper: false
      - run: tofu fmt -check -recursive
      - run: tofu init -backend=false -input=false -lockfile=readonly
      - run: tofu validate
      - run: tofu test -no-color
